### ISSUE TITLE
Support Intel SDE version 9.14, released 2022-10-25

### ISSUE THREAD

**Issue by barrbrain** [petarpetrovt/setup-sde#24]
See [Intel Software Development Emulator Release Notes](https://www.intel.com/content/www/us/en/developer/articles/release-notes/intel-software-development-emulator-release-notes.html) and the [Intel® Software Development Emulator](https://www.intel.com/content/www/us/en/download/684897/intel-software-development-emulator.html) download page.

**Comment by petarpetrovt** [comment]
Fixed in release `v2.1` .

It appears that Intel SDE `9.14` does not have a version available for `macOS`. Therefore, the `9.14.0` version of `setup-sde` will only be compatible with `Windows` and `Linux` operating systems.
