### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by animetosho** [petarpetrovt/setup-sde#27]
Firstly, thanks for this action!

I can't seem to get it working on Windows unfortunately.  
Doing a `dir $env:SDE_PATH` command after the action results in a `Cannot find path` error.

I'm guessing that the TAR extract fails, though that section of the action doesn't error. I've tried both the .xz and .bz2 archives.

**Comment by petarpetrovt** [comment]
I am on a vacation atm, will check it next week

**Comment by petarpetrovt** [comment]
I have added support for the latest Intel SDE `9.24.0`, all tests ([check this step](https://github.com/petarpetrovt/setup-sde/actions/runs/6080986842/job/16495820073#step:7:11)) seems to be working.

**Comment by animetosho** [comment]
Thanks!

I think I messed up my action, causing it to fail. Sorry, my mistake!
